### ISSUE TITLE
Default Rules/Rulesets not defined 

### ISSUE THREAD

**Issue by arougthopher** [opena11y/fae2#2]
It appears as if the app is looking to have some default data in its repository.  However, none are provided.  I have fae2 running on sqlite3, and created the schema within the database by doing a migrate command, but now I need to add the default data required to run properly.  Can you provide that in your repository as well?

**Comment by jongund** [comment]
It is in the populate directory.

**Comment by arougthopher** [comment]
Thank you, sorry I missed that!
