### ISSUE TITLE
Provide deeper spidering

### ISSUE THREAD

**Issue by jongund** [opena11y/fae2#25]
Increase level of spidering of websites, maybe useful with the new page limit option

**Comment by creativetorch** [comment]
Depending on the level and options for crawling, it could use a lot of server resources to crawl deeper... I would add the option to start, pause, and stop crawling.

**Comment by jongund** [comment]
Can you send a URL that has deep linking for testing

**Comment by jongund** [comment]
Available in Version 2.0.0-beta.3, but need to ask admin to upgrade account type
