### ISSUE TITLE
Fail to run report as Admin user on clean database/install

### ISSUE THREAD

**Issue by arougthopher** [opena11y/fae2#3]
Either as a logged in Admin User or Anonymous, when trying to run a report, the following error is thrown:

```
Request Method: 	POST
Request URL: 	    http://localhost:8080/
Django Version: 	1.9.1
Exception Type: 	IntegrityError
Exception Value: 	null value in column "delete" violates not-null constraint
```

at line 219 in reports/models.py

**Comment by arougthopher** [comment]
I removed the "NOT NULL" constraint on the "delete" column that was added to reports_websitereport and it was able to proceed, however, it does not appear to have done anything.

The delete column was added in 0005_websitereport_delete.py migration, but does not appear to be referenced in the models.py.

**Comment by jongund** [comment]
You need to make sure that you are also running "python process_evaluation_requests.py" in the "fae-util" directory in parallel with the django applciation
