### ISSUE TITLE
Which Python?

### ISSUE THREAD

**Issue by binarygod** [opena11y/fae2#42]
In the Requirements Python 2.7 is listed, in the Apache config it looks like a Python 3.4 Virtual Env is created.  What are the actual requirements?

**Comment by jongund** [comment]
I am using Python 2.7

Job

Jon  Gunderson
Sent from my iPhone

On Feb 17, 2017, at 8:46 AM, Tim Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


In the Requirements Python 2.7 is listed, in the Apache config it looks like a Python 3.4 Virtual Env is created. What is the actual requirements?

**Comment by binarygod** [comment]
Thank you!
