### ISSUE TITLE
process_evaluation_requests

### ISSUE THREAD

**Issue by binarygod** [opena11y/fae2#44]
Hello, after much trail I have FAE running locally, I was able to successfully scan one site, but don't remember the circumstances of that instance.  Now when scanning a site I get the following in the data/admin log for that report.

[SAVE WEBSITE][**ERROR]: Error: saving to django

Could you point me in a direction?  Thanks!

**Comment by binarygod** [comment]
Sorry, forgot to add the relevant log information:
`[SAVE WEBSITE][info   ]: Processing File: status.txt
[SAVE WEBSITE][info   ]: Processing File: faeUtil-0000.json
[SAVE WEBSITE][info   ]: URL: https://firstnbank.com/
[SAVE WEBSITE][info   ]: Processing File: authorizationStatus.txt
[SAVE WEBSITE][info   ]: Processing File: processed_urls.csv
[SAVE WEBSITE][info   ]: Processing File: processed_urls.txt
[SAVE WEBSITE][info   ]: Processing File: oaa_a11y_config.js
[SAVE WEBSITE][info   ]: ========================================================
[SAVE WEBSITE][info   ]: [WebsiteResult][saveToDjango] Website Report: FNB2
[SAVE WEBSITE][info   ]: [WebsiteResult][saveToDjango]: Saving Rule Category Results
[SAVE WEBSITE][info   ]: [WebsiteResult][saveToDjango]: Saving Guideline Results
[SAVE WEBSITE][info   ]: [WebsiteResult][saveToDjango]: Saving Rule Scope Results
[SAVE WEBSITE][info   ]: [WebsiteResult][saveToDjango]: Saving Rule Results
[SAVE WEBSITE][info   ]: [WebsiteResult][saveToDjango]: Saving Page Results
[SAVE WEBSITE][info   ]: [WebsiteResult][saveToDjango]: Done Saving Results
[SAVE WEBSITE][info   ]: Set status complete
[SAVE WEBSITE][info   ]:           Pages saved: 1
[SAVE WEBSITE][info   ]:            Total Time:     1.0996
[SAVE WEBSITE][info   ]: Average time per page:     1.0996 seconds/page (1 page)
[SAVE WEBSITE][info   ]: [SAVE_WEBSITE_RESULTS] Saving StatsAll: All Years
[SAVE WEBSITE][**ERROR]: Error: saving to django
`

**Comment by binarygod** [comment]
Figured this one out, noticed each report failed at Saving StatsAll, took a look at the database and the Stats Year table had two 2017's, removed it and everything is working fine.

**Comment by jongund** [comment]
Tim,

Just curious.   What is your interest/purpose in running your own copy of FAE 2.0?

Also there will be some rule updates in the next week, so be prepared to update the rules.

Jon
